spring:
    profiles:
        active: local
    application:
        name: TicketBooking
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        properties:
            hibernate:
                ddl-auto: none
                format_sql: true
    flyway:
        enabled: true
        url: ${FLYWAY_URL}
        user: ${FLYWAY_USER}
        password: ${FLYWAY_PASSWORD}
        cleanDisabled: false
        schemas: ticket_booking

    security:
        enabled: false

jwt:
    secret: ${JWT_SECRET}
    lifetime: 60m

